repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.2
    hooks:
      - id: check-metaschema
        files: ^{syntaxes/.*\.json}$
      - id: check-dependabot
      - id: check-github-actions
      - id: check-github-workflows
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.1
    hooks: [id: actionlint]
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks: [id: yamllint]
  - repo: https://github.com/standard/standard
    rev: v17.1.0
    hooks: [id: standard]
