name: release-please
on:
  workflow_dispatch:  # trigger manually for debugging
  push: {branches: [main]}

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          # a token is needed to trigger other workflows on release
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: node
