name: Visual Studio Code Publish Extension
on:
  workflow_dispatch:
  release: {types: [published]}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VSCE_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
